version: '1.0'

services:
  walletapp.api:
    image: hunter3/wallet-api
    ports:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
     - db
  db:
     container_name: pg_db
     image: postgres:latest
     environment:
       POSTGRES_USER: root
       POSTGRES_PASSWORD: root
       POSTGRES_DB: my_db
     ports:
      - "5432:5432"
  pgadmin:
     container_name: pgadmin
     image: dpage/pgadmin4
     environment:
       PGADMIN_DEFAULT_EMAIL: user@email.com
       PGADMIN_DEFAULT_PASSWORD: admin
     ports:
       - "5050:80"
